---
output: 
  flexdashboard::flex_dashboard
params:
  gs_dir: ""
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
```

```{r libraries, include=FALSE}
library(HIPCCyto)
library(flowWorkspace)
library(ggcyto)
library(plotly)
library(htmltools)
library(htmlwidgets)
```

```{r load, include=FALSE}
gs <- load_gs(file.path(params$gs_dir, "gs"))
pd <- pData(gs)
outliers <- HIPCCyto:::find_outliers(gs)
pd$outlier <- pd$name %in% outliers
pData(gs) <- pd
s <- summarize_gating_set(gs)
```

---
title: `r s$study`
---

Summary
===================================== 

Column
-------------------------------------

### Summary

```{r summary}
knitr::kable(
  data.frame(
    "n_samples" = length(gs),
    "n_markers" = length(markernames(gs)),
    "n_participants" = length(unique(pd$participant_id))
  ),
  align = "c"
)
```

### Gating Hierarchy

```{r nodes}
flowWorkspace::plot(gs)
```

### Panel

```{r panel}
m <- markernames(gs)
knitr::kable(data.frame(Channel = names(m), Marker =  m, row.names = NULL))
```

Column {.tabset}
-------------------------------------

### Study info

```{r study-info}
ImmPortR:::query(sprintf("study/summary/%s", s$study))
```

### Tables

#### Sample types

```{r sample-types}
table(pd$type)
```

#### Timepoints

```{r timepoints}
table(paste(pd$study_time_collected, pd$study_time_collected_unit))
```

#### Cohorts

```{r cohorts}
table(pd$cohort)
```

#### Batches

```{r batches}
table(pd$batch)
```

### Custom processing parameters

```{r parameters}
HIPCCyto:::DATA[[s$study]]
```



Gating
=====================================

Column {.tabset}
-------------------------------------

### Gating Hierarchy

```{r gating-hierarchy}
flowWorkspace::plot(gs)
gates <- HIPCCyto:::get_nodes(gs)
```

### Live gates

```{r live}
if ("Live" %in% gates) {
  suppressWarnings(p <- qc_gates(gs, "Live"))
  ggplotly(p) %>%
    onRender("
      function(el) {
        el.on('plotly_click', function(d) { 
          txt = d.points[0].text.split('<br />');
          console.log(txt);
          i = txt[txt.length - 1].trim();
          id = txt.filter(v => /sample/.test(v))[0].replace('sample: ', '');
          id = id.substring(0, id.search('.fcs')+4).trim();
          console.log(id);
          $('.dropdown-menu li.active').removeClass('active');
          $('.dropdown-tab').parent('li').eq(i-1).addClass('active');
          $('#samples div.active').removeClass('active');
          $('#' + CSS.escape(id)).addClass('active');
          
          window.open('#pdata', '_self');
          var checkExist = setInterval(function() {
            if ($('input[type=search]').length > 0) {
              $('input[type=search]').val(id).keyup();
              clearInterval(checkExist);
            }
          }, 100);
          window.open('#by-sample', '_self');
        });
      } 
    ")
} else {
  print("no Live gates")
}
```

### Non-debris gates

```{r nondebris}
if ("Nondebris" %in% gates) {
  suppressWarnings(p <- qc_gates(gs, "Nondebris"))
  ggplotly(p) %>%
    onRender("
      function(el) {
        el.on('plotly_click', function(d) { 
          txt = d.points[0].text.split('<br />');
          console.log(txt);
          i = txt[txt.length - 1].trim();
          id = txt.filter(v => /sample/.test(v))[0].replace('sample: ', '');
          id = id.substring(0, id.search('.fcs')+4).trim();
          console.log(id);
          $('.dropdown-menu li.active').removeClass('active');
          $('.dropdown-tab').parent('li').eq(i-1).addClass('active');
          $('#samples div.active').removeClass('active');
          $('#' + CSS.escape(id)).addClass('active');
          
          window.open('#pdata', '_self');
          var checkExist = setInterval(function() {
            if ($('input[type=search]').length > 0) {
              $('input[type=search]').val(id).keyup();
              clearInterval(checkExist);
            }
          }, 100);
          window.open('#by-sample', '_self');
        });
      } 
    ")
} else {
  print("no Nondebris gates")
}
```

### Lymphocytes gates

```{r lymphocytes}
if ("Lymphocytes" %in% gates) {
suppressWarnings(p <- qc_gates(gs, "Lymphocytes"))
ggplotly(p) %>%
  onRender("
    function(el) {
      el.on('plotly_click', function(d) {
        txt = d.points[0].data.text.split('<br />');
        console.log(txt);
        i = txt[txt.length - 1].trim();
        id = txt.filter(v => /sample/.test(v))[0].replace('sample: ', '');
        id = id.substring(0, id.search('.fcs')+4).trim();
        console.log(id);
        $('.dropdown-menu li.active').removeClass('active');
        $('.dropdown-tab').parent('li').eq(i-1).addClass('active');
        $('#samples div.active').removeClass('active');
        $('#' + CSS.escape(id)).addClass('active');
        
        window.open('#pdata', '_self');
        var checkExist = setInterval(function() {
          if ($('input[type=search]').length > 0) {
            $('input[type=search]').val(id).keyup();
            clearInterval(checkExist);
          }
        }, 100);
        window.open('#by-sample', '_self');
      });
    } 
  ")
} else {
  print("no Lymphocytes gates")
}
```



By sample
===================================== 

```{r samples}
sample_names <- sampleNames(gs)
plotInfo <- lapply(
  seq_along(sample_names), 
  function(i) {
    list(
      name = sample_names[i],
      i = i,
      gates = rmarkdown:::base64_encode_file(file.path(params$gs_dir, sprintf("gates/%s.png", sample_names[i])), base64enc::base64encode),
      spillover = rmarkdown:::base64_encode_file(file.path(params$gs_dir, sprintf("spillover/%s.png", sample_names[i])), base64enc::base64encode)
    )
  })
```

<div id="plots">
<div class="dropdown">
<button class="dropdown-toggle" type="button" data-toggle="dropdown">
Select Sample
<span class="caret"></span>
</button>
<ul class="dropdown-menu">
      
```{r dropdown}
tagList(
  lapply(
    plotInfo,
    function(thisPlotInfo) {
      if (thisPlotInfo$name == plotInfo[[1]]$name) {
        class <- "active"
      } else {
        class <- ""
      }
      tags$li(
        class = class,
        tags$a(
          id = thisPlotInfo$name,
          href = "#by-sample",
          class = "dropdown-tab",
          thisPlotInfo$name
        )
      )
    }
  )
)
```
      
</ul>
</div>
<div class="tab-content", id="samples">
    
```{r tabs}
tagList(
  lapply(
    plotInfo, 
    function(thisPlotInfo) {
      if (thisPlotInfo$name == plotInfo[[1]]$name) {
        class <- "tab-pane active"
      } else {
        class <- "tab-pane"
      }
      div(
        id = thisPlotInfo$name,
        class = class,
        h3(thisPlotInfo$name),
        div(
          class = "sample-row",
          style = "display: flex;",
          div(
            class = "sample-column",
            style = "flex: 50%; padding: 5px;",
            h5("Gates"),
            img(src = thisPlotInfo$gates, style = "height: 100%; width: 100%; object-fit: contain")
          ),
          div(
            class = "sample-column",
            style = "flex: 50%; padding: 5px;",
            h5("spillover matrix"),
            img(src = thisPlotInfo$spillover, style = "height: 100%; width: 100%; object-fit: contain")
          )
        )
      )
    }
  )
)
```
</div>
</div>

<style>
.dropdown-menu {
   max-height:200px;
   overflow:scroll; 
}
</style>

<script type='text/javascript'>
// This makes the dropdown work  
$('.dropdown-tab').click(function (e) {
    $('.dropdown-menu li.active').removeClass('active');
    $(this).parent('li').addClass('active');
    $('#samples div.active').removeClass('active');
    $('#' + CSS.escape($(this).attr('id'))).addClass('active');
    id = $(this).attr('id');
    
    window.open('#pdata', '_self');
    var checkExist = setInterval(function() {
      if ($('input[type=search]').length > 0) {
        $('input[type=search]').val(id).keyup();
        clearInterval(checkExist);
      }
    }, 100);
    window.open('#by-sample', '_self');
})
</script>



Marker expression
=====================================

Column {.tabset}
-------------------------------------

### After lymphocyte gate

```{r markers}
img(
  src = rmarkdown:::base64_encode_file(file.path(params$gs_dir, "markers.png"), base64enc::base64encode),
  style = "height: 100%; width: 100%; object-fit: contain"
)
```



Sample metadata
=====================================

```{r pData}
DT::datatable(pd)
```



Session info
===================================== 

```{r session-info}
sessionInfo()
```



Help
===================================== 

Column {.tabset}
-------------------------------------

### Summary

### Gating

### By sample

### Marker expression

### Sample metadata

### Session info

### Help



<style type="text/css"> div.chart-shim { overflow: auto } </style>
